import type { MetadataRoute } from "next";

const SITE_URL = "https://www.ustowaiconnect.com";

// Serves /robots.txt — allows crawling of public pages, keeps the app's
// private/authenticated areas out of the index, and points crawlers at the
// sitemap generated by app/sitemap.ts.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/admin",
        "/super-admin",
        "/onboarding",
        "/accept-invite",
        "/auth-callback",
        "/driver",
        "/api/",
      ],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
